### ISSUE TITLE
Multiple date pick

### ISSUE THREAD

**Issue by Lukas182** [mattmorgan6/TwoWeekControl#1]
Is it possible to pick more than one date ?

Thanks!

**Comment by mattmorgan6** [comment]
Hi @Lukas182, it is only possible to pick one date.
If you'd like to implement the feature yourself, you can fork this repo for a complete Xamarin app, or fork the repo [here](https://github.com/mattmorgan6/ModernXamarinCalendar) for just the package files.

Thanks for reaching out!
